---
# http://elixir-lang.org/install.html
- name: add Erlang Solutions repo
  get_url: url=https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb
           dest=/tmp/erlang-solutions_1.0_all.deb
- apt: deb=/tmp/erlang-solutions_1.0_all.deb

- name: apt-get update
  apt: update_cache=yes

- name: install elixir
  apt: name=elixir state=latest
